#!/usr/bin/env node
/**
 * headlines.mjs — build HEADLINES.md, an index of every headline in the archive.
 *
 *   node scripts/headlines.mjs [--out HEADLINES.md]
 *
 * Reads the edition.md files rather than the PDFs, so run it after
 * `npm run extract`. The front-page headline of each issue comes from
 * editions.json, which is curated; the rest are the headings the extractor
 * found, minus the furniture — masthead, folios, letter-spaced section rules.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(import.meta.url), '../..');

const outArg = (() => {
  const i = process.argv.indexOf('--out');
  if (i === -1) return 'HEADLINES.md';
  const v = process.argv[i + 1];
  if (!v || v.startsWith('--')) {
    console.error('--out needs a path, e.g. --out HEADLINES.md');
    process.exit(1);
  }
  return v;
})();

const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'editions.json'), 'utf-8'));

// ---------------------------------------------------------------- filtering

const MASTHEAD = /^(𝔗𝔥𝔢|𝔓𝔥𝔦𝔩|ℭ𝔥𝔞𝔱|𝔗𝔦𝔪𝔢𝔰|the|phil|chat|times)$/i;

/**
 * Is this heading a real headline rather than page furniture?
 *
 * The extractor classifies by type size, which cannot tell a headline from the
 * masthead set in the same size, or from a folio, or from the letter-spaced
 * rules the paper uses to label a section. Those are what this drops.
 */
function isHeadline(text) {
  const clean = text.trim();
  if (clean.length < 8) return false;

  // The masthead arrives a word at a time when it is set across the page.
  const words = clean.split(/\s+/);
  if (words.every((w) => MASTHEAD.test(w))) return false;

  // Letter-spaced furniture: "S C I E N C E & E T H I C S", "P A G E  5".
  const singles = words.filter((w) => w.length === 1).length;
  if (words.length >= 4 && singles / words.length > 0.5) return false;

  // Folios, prices, dates standing alone.
  if (/^(vol|page|price|continued|fig)\b/i.test(clean)) return false;
  if (!/\p{L}{3}/u.test(clean)) return false;

  return true;
}

// ---------------------------------------------------------------- read

// Words no headline ends on. A line breaking after one of these is a headline
// set over two lines whose halves the extractor could not see were one.
const CONTINUES = new Set([
  'a', 'an', 'and', 'as', 'at', 'but', 'by', 'for', 'from', 'his', 'her', 'in',
  'into', 'is', 'it', 'its', 'not', 'of', 'on', 'or', 'over', 'that', 'the',
  'their', 'they', 'to', 'was', 'were', 'who', 'with', 'you', 'your',
]);

/** Does this heading run on into the next one? */
function runsOn(text) {
  const clean = text.trim();
  if (/[‐­-]$/.test(clean)) return true;
  // A clause left open — "'ARGENTINA HAD 14 PLAYERS,' / ENGLAND SUPPORTER
  // REPORTS" — counting a closing quote as part of the punctuation.
  if (/,["'”’]?$/.test(clean)) return true;
  const last = clean.split(/\s+/).pop() || '';
  return CONTINUES.has(last.replace(/[^\p{L}]/gu, '').toLowerCase());
}

/** Pull the headings out of an edition.md, keeping the page they sat on. */
function headingsOf(markdown) {
  const found = [];
  let page = null;
  for (const raw of markdown.split(/\r?\n/)) {
    const line = raw.trim();
    const pageMatch = line.match(/^## Page (\d+)$/);
    if (pageMatch) {
      page = Number(pageMatch[1]);
      continue;
    }
    // ### is a headline, #### a secondary deck; ##### is a crosshead, too fine
    // grained for an index.
    const headMatch = line.match(/^(#{3,4}) (.+)$/);
    if (!headMatch || page === null) continue;
    const text = headMatch[2].trim();
    if (!isHeadline(text)) continue;
    if (found.some((f) => f.text === text)) continue;

    const deck = headMatch[1].length === 4;
    const previous = found[found.length - 1];
    if (previous && previous.page === page && previous.deck === deck && runsOn(previous.text)) {
      // A headline breaks at a hyphen it already had — "THE THIRTY-ELEPHANT
      // MARRIAGE" — so the hyphen stays and no space goes in after it.
      previous.text = /[‐­-]$/.test(previous.text)
        ? previous.text + text
        : `${previous.text} ${text}`;
      continue;
    }
    found.push({ page, text, deck });
  }
  return found;
}

function formatDate(dateStr) {
  return new Date(dateStr + 'T12:00:00').toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

// ---------------------------------------------------------------- write

const out = [];
out.push('# 𝔗𝔥𝔢 𝔓𝔥𝔦𝔩 ℭ𝔥𝔞𝔱 𝔗𝔦𝔪𝔢𝔰 — headlines');
out.push('');
out.push('Every headline in the archive, newest issue first.');
out.push('');
out.push(
  'Generated by `scripts/headlines.mjs` from the `edition.md` files. Run ' +
    '`npm run extract` first if an edition is missing, then `npm run headlines`.'
);
out.push('');

const editions = [...manifest.editions].sort((a, b) => b.date.localeCompare(a.date));
let total = 0;

for (const edition of editions) {
  const mdPath = path.join(ROOT, 'editions', edition.slug, 'edition.md');
  out.push('---');
  out.push('');
  out.push(`## ${edition.title} — ${formatDate(edition.date)}`);
  out.push('');
  out.push(`**${edition.headline}**`);
  out.push('');

  if (!fs.existsSync(mdPath)) {
    out.push(`*No \`edition.md\` yet — run \`npm run extract\`.*`);
    out.push('');
    continue;
  }

  const headings = headingsOf(fs.readFileSync(mdPath, 'utf-8'));
  total += headings.length;
  out.push(
    `${edition.pages} pages · [PDF](editions/${edition.slug}/edition.pdf) · ` +
      `[markdown](editions/${edition.slug}/edition.md) · ${headings.length} headlines`
  );
  out.push('');

  let page = null;
  for (const heading of headings) {
    if (heading.page !== page) {
      page = heading.page;
      if (out[out.length - 1] !== '') out.push('');
      out.push(`**Page ${page}**`);
      out.push('');
    }
    out.push(`- ${heading.deck ? `*${heading.text}*` : heading.text}`);
  }
  out.push('');
}

fs.writeFileSync(path.join(ROOT, outArg), out.join('\n'), 'utf-8');
console.log(`wrote ${outArg} — ${editions.length} editions, ${total} headlines`);
